### PR TITLE
Add better quality desktop icon

### LINKED ISSUE #50: Desktop icon quality too low
The current desktop icon has a non-standard 42x42 px size that is too small and low quality for today's Linux desktop standards. Please, update it.

### PR DESCRIPTION
**Pull request by AsciiWolf**
This PR adds a better quality, standard size desktop icon upscaled from the original one.

It is already used in the [Fedora](https://src.fedoraproject.org/rpms/qsstv/c/27ef9a7a6e3b6176c3b7ee2914ce9b8243a8394d?branch=rawhide), [Debian](https://salsa.debian.org/debian-hamradio-team/qsstv/-/commit/e3e9378311bf78afeeb2aa3f488dcfde3b9cba48) and [Flathub](https://flathub.org/apps/net.qsl.QSSTV) QSSTV packages.

Fixes #50.

@ON4QZ Feel free to review and merge. Let me know if there is any problem. Thanks! :-)

### CODE REVIEW

**Comment by AsciiWolf** [comment]
@ON4QZ Were you able to take a look at this? Thanks!

**Comment by dl8dtl** [comment]
Looks good to me. If there are no objections, I can merge it.

**Comment by AsciiWolf** [comment]
@dl8dtl Tested and works fine. :-) Feel free to merge.

**Pull request merged**
