### PR TITLE
Template is re-applied before sending

### PR DESCRIPTION
**Pull request by Ruxton**
Template is re-applied before sending to regenerate %t macro and ensure any changes since loading the image are represented.

### CODE REVIEW

**Comment by dl8dtl** [comment]
Shouldn't that also apply to %d?

**Comment by dl8dtl** [comment]
Or is that already implied anyway? (I only looked at the patch so far, not the full context.)

**Comment by Ruxton** [comment]
It applies to all of them, it just runs the applyTemplate() func before sending. Many wont change in a session, but %t is mostly the reason i did this. I mostly send in a net and I'll add an image 5 minutes before my turn to transmit, so the template with timestamp in it was always off. I've been running with this in for about a year.

**Comment by dl8dtl** [comment]
Sounds useful to me.

**Pull request merged**
